---
title: "Week 8"
author: "DJM"
date: "3 March 2020"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, rladies, rladies-fonts, extra.css]
    nature:
      beforeInit: ["macros.js", "https://platform.twitter.com/widgets.js"]
      titleSlideClass: [center,middle, inverse, bigger]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---


# News discussion



.center[.bigger[
[The Southern Diet Causes High Blood Pressure](https://www.npr.org/sections/thesalt/2018/10/02/653798353/southern-diet-blamed-for-high-rates-of-hypertension-among-blacks)
]]


--

.center[.bigger[

[Does it?](https://blackgirlsguidetoweightloss.com/the-study-guide/this-is-what-white-supremacy-in-medical-research-looks-like/?fbclid=IwAR2b2S6Qgcd6dnn0cslZ-oqBXgNJGIQrejr9HsmrkOhFAkS-qWkxbe__-x8)

]]

---

class: even-smaller

.pull-left[

__Out of how many__
: Numbers are magnitudes. It often helps to interpret if we convert these to ratios. For example, rather than knowing the number of murders in a city it may help to compare to the population of the city (murders per 100,000 residents, say).

__Compare with rates, but be careful__
: Related to "out of how many", it's often more useful to examine rates. But these can be counterintuitive if "how many" is relatively small.

__Clumping/streaks__
: Pure random process produce streaks or clumps. This isn't necessarily a sign of some thing real. Think a coin that lands heads 5 times in a row out of 10 or a roulette wheel that lands on "odds" 6 times.

__Independence/Dependence__
: It's easy to calculate the probabilities of independent events all occurring: just multiply. But be careful to make sure the events are independent!

__Sunk costs__
: Be wary of making decisions based on past decisions you can't change. Don't bet in poker based on past losses. Don't stay with your significant other just because you've been together for a while.

__Decision making with uncertainty__
: Try to determine the utility you'll earn for each possible outcome. How likely are those outcomes? Make the decision with a higher expected utility.

__Regression to the mean__
: Other things equal, performance below the average is likely to be followed by relatively higher performance. Performance above the average is likely to be followed by relatively lower performance.

__Color scaling__
: Be aware of the point you're trying to make. Is it apparent? Be aware of colorblindness (about 10% of men and 4% of women).

__Expected value__
: Mathematically, the sum of all potential values weighted by the probability of seeing those values. For example, the expected number of heads in 2 flips of a fair coin is
$$EV = 0\times \frac{1}{4} + 1\times \frac{2}{4} + 2\times \frac{1}{4} = 1$$

__Law of large numbers__
: As you repeat a process over and over and over forever, the running average will get closer and closer to the expected value.

__Simpson's paradox__
: a trend appears in several different groups of data but disappears or reverses when these groups are combined

__Hypothesis test__
: if the _null hypothesis_ is true, would we expect to see data like this? If yes, then stick with the status quo. If no, then we reject the null in favor of the _alternative_.

__Null hypothesis__
: The current state of our understanding. The presumed truth. The thing we want to falsify.

__Alternative hypothesis__
: The thing we wish to prove. Think _null_ $=$ innocent, _alternative_ $=$ guilty.

__P-value__
: Given that the null is true, what is the probability of our observed data, or something more extreme

__Statistical significance__
: if the p-value is "small enough", we call the effect "statistically significant"

__Margin of error__
: we have an estimate of something (say a poll that shows 30% support), but how much might that estimate vary? This range is the "margin of error"

__Graphics__
: scaling, coloring, axes, percentages, etc. Does this graphic make the point clearly? Does it obscure alternative interpretations to manipulate?

]

.pull-right[

__Proportionality principle__
: If various alternatives are equally likely, and then some event is observed, the updated probabilities for the alternatives are proportional to the probabilities that the observed event _would_ have occurred under those alternatives.

__Sample space__
: An enumeration of the possible outcomes of a process.

__Foxy forecasting__
: drawing on a wide variety of experiences and evidence to make predictions rather than using the lens of a single guiding idea

__Reproducible research__
: Work which can be easily replicated by another researcher or group by taking in the original data and running a series of well-described codes

__Peer review__
: The process by which other experts evaluate and ascertain whether the results described can be widely accepted within a research community as valid

__Mean vs Median__
: The mean or average is the sum of all the observations divided by the number of observations. The median is the value that splits the data into two equal sized parts. The mean is influenced by very large or small values, outliers, while the median is not. The median is more _robust_ to abberant values.

__Forecast horizon__
: How far in the future you're making predictions. Generally, the farther ahead you try to predict, the more uncertain you are.

__Forecast uncertainty__
: When you make a prediction, you want to think about sources and sizes of possible errors. How accurate is your prediction?

__Model averaging__
: Combining information from lots of different sources to make a prediction. This is "foxy".

__Histogram__
: A graphical display of possible values along with the observed frequencies of those values.

__Bias__
: The difference between the truth and your estimate, on average.

__Variance__
: How much does your estimate vary around the truth, on average.

__Over-fitting and Under-fitting__
: Using too complex (over) or too simple (under) a method of analysis for the amount of data you have.

__Power law__
: a relationship wherein a relative change in one quantity results in a proportional relative change in the other quantity. For example, the side-length and the area of a square follow a power law relationship.

__Correlation vs. Causation__
: correlation measures the strength of a linear association between two quantities. Contrast this with the statement that manipulating one quantity results in a meaningful change in the other

__Hidden common causes__
: It is difficult to determine if one thing causes another purely through observation. We need to manipulate one to watch for an effect. If we simply observe, it is hard to rule out hidden factors that may cause both to change.

__Bayesian__
: Using "prior" information to think about predictions and uncertainty. As we collect data, we update our existing beliefs to incorporate this new evidence into our understanding.

__Sampling__
: How are the data collected? Some different types of samples are the _random sample_ or the _convenience sample_.

]


---

class: middle, center, inverse

<iframe width="960" height="540" src="https://www.youtube.com/embed/1aheRpmurAo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

